group=priv.seventeen.artist.symphony
version=1.0.0-SNAPSHOT
kotlinVersion=1.8.22
blinkVersion=1.3.14
ariaVersion=1.1.19
asteroidVersion=1.2.2
spigotVersion=1.18.2-R0.1-SNAPSHOT
overtureVersion=1.0.0

# Maven
mavenRepoUrl=https://repo.arcartx.com/repository/maven-releases/
mavenRepoUser=admin

org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.parallel=false
kotlin.code.style=official
